name: tmdb_trending
description: This is an infinity scroll view example application using the tmdb api to show the trending movies of the week.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  unicons: ^2.0.2
  flutter_svg: ^1.0.3
  dartz: ^0.10.1
  shimmer: ^2.0.0
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  flutter_modular: ^4.4.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/empty_svg.svg